# Generated by Django 3.2.5 on 2021-12-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='bmi',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
