# Generated by Django 3.2.5 on 2021-12-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_data_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='bmi',
            field=models.FloatField(null=True),
        ),
    ]
