# Generated by Django 3.2.5 on 2021-12-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_data_bmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='smoker',
            field=models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Yes')], null=True),
        ),
    ]
